/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/solve/algorithms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Algorithms */
        get: operations["get_algorithms_solve_algorithms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solve/{algorithm}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solve */
        post: operations["solve_solve__algorithm__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Board
         * @description A 9x9 Sudoku grid. 0 marks an empty cell.
         */
        Board: {
            /**
             * Cells
             * @description 9 rows of 9 cells each; 0 = empty, 1-9 = filled.
             */
            cells: number[][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** SolveResult */
        SolveResult: {
            /**
             * Solved
             * @description whether the returned board is a complete, valid solution
             */
            solved: boolean;
            solved_board: components["schemas"]["Board"];
            /** Steps */
            steps: components["schemas"]["SolveStep"][];
            stats: components["schemas"]["SolveStats"];
        };
        /** SolveStats */
        SolveStats: {
            /** Algorithm */
            algorithm: string;
            /**
             * Elapsed Time
             * @description server-measured compute seconds, independent of animation speed
             */
            elapsed_time: number;
            /** Step Count */
            step_count: number;
            /**
             * Given Count
             * @description number of non-zero cells in the input puzzle
             */
            given_count: number;
        };
        /**
         * SolveStep
         * @description One diff in a solver's trace: a single cell placed or un-placed.
         *
         *     Degenerate solvers (e.g. an ML solver that jumps straight from empty to
         *     solved) may return zero or one step — the visualizer must tolerate that.
         */
        SolveStep: {
            /**
             * Action
             * @enum {string}
             */
            action: "place" | "remove";
            /**
             * Cell
             * @description (row, col), both 0-8
             */
            cell: [
                number,
                number
            ];
            /**
             * Value
             * @description value placed/removed, 1-9
             */
            value?: number | null;
            /** Candidates Removed */
            candidates_removed?: number[];
            /** Reasoning */
            reasoning?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_algorithms_solve_algorithms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    solve_solve__algorithm__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                algorithm: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Board"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
